name: Deploy Website
on: [push]

jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Updating Ubuntu repos
        run: apt update
      
      - name: Install Hugo
        run: apt install hugo -y
      
      - name: Create public directory
        run: mkdir /public

      - name: Clone repo
        run: actions/checkout@v4
      
      - name: Build Website
        run: hugo
