name: Deploy Website
on: [push]

jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Updating Ubuntu repos
        run: apt update
      
      - name: Install Docker
        run: apt install docker.io -y && apt install docker-buildx -y

      - name: Install Hugo
        run: apt install hugo -y
      
      - name: Create public directory
        run: mkdir /public

      - name: Clone repo
        uses: actions/checkout@v5
      
      - name: Build Website
        run: hugo

      - name: Link Docker to Gitea Container Registry
        run: docker login --username beforethesurge --password ${{ secrets.GT_PASS }} gitea:3000

      - name: Build Container
        run: docker buildx build -t gitea:3000/beforethesurge/website:latest .

      - name: Push Container to Container Registry
        run: docker push gitea:3000/beforethesurge/website:latest
